install:
  - pip install --user awscli
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.1/hugo_0.55.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - hugo version
before_script:
  - rm -rf public
  - hugo
script:
  - aws s3 sync public/ s3://omgkyle.com --acl public-read --delete
  - aws cloudfront create-invalidation --distribution-id E35KTKN89BY92N --paths '/*'
branches:
  only:
    - master